### ISSUE TITLE
Instructions on hardware

### ISSUE THREAD

**Issue by getrav** [nhauber99/PriorArt#1]
I have a DIY photometric stereo scanner we use for our products and we Substance 3D suite to create all the maps.
I am having issues with shiny fabrics as the reflections change the actual color output.  As suggested by you I am installing a CPL for both the lights and the camera today.

Your version accounts for many of the issues I am having. Would you share the parts list, pcb designs, and instructions if any. If you don't have instructions, I would be happy to build one and document the process for you and the community. I think this is a really useful device and the software is included wow!

**Comment by nhauber99** [comment]
Hi, the cross polarization should indeed get rid of some of the issues you seem to be having. But keep in mind that the orientation of the CPL filter matters as it consists of a quarter wave plate and a linear polarizer, so if you're not really seeing an effect no matter how you rotate the filters, then flip the ones in front of the lights (or use only a linear polarizer for the lights).

The version described in this document is more of a concept though and I haven't implemented most of the ideas listed. My scanner(s) implementing some of the features are still in development though and I'm currently not planning on making the software or hardware design itself open source, sorry.
